export const LANGUAGE_ICONS = {
  html: '</>',
  css: '{  }',
  javascript: '{  }',
  c: 'C',
  cpp: 'C++',
  csharp: 'C#',
  python: '_',
  java: '☕',
  php: '<?php ?>',
  rust: '🦀',
  go: 'Go',
  swift: 'nil',
  clojure: 'λ',
  haskell: 'λ',
  fsharp: 'F#',
  assembly: '⚙️',
  basic: 'B',
  cobol: 'COBOL',
  fortran: 'F',
  lisp: 'λ',
  pascal: 'P',
  brainfuck: 'BF',
  emojicode: '😀',
  jsfuck: 'JSF',
  omgrofl: '😂',
  shakespeare: '🎭',
  false: 'FALSE',
  elixir: '💧',
  elm: '🌳',
  erlang: 'E',
  'objective-c': 'ObjC',
  csh: 'CSH',
  holyc: 'HC',
};